const tasks = [
    'cleaning',
    'cooking',
    'laundry',
    'grocery shopping',
    'exercise',
    'meditation',
    'reading',
    'email management',
    'bill payments',
    'gardening',
    'car maintenance',
    'meal prep',
    'organizing closet',
    'vacuum cleaning',
    'dusting',
    'window washing',
    'trash disposal',
    'pet care',
    'water plants',
    'budget planning',
    'schedule appointments',
    'backup files',
    'social media management',
    'networking',
    'learn new skill',
    'home repairs',
    'journal writing',
    'update calendar',
    'phone calls',
    'document filing'
    ];